version: 0.2
env:
  variables:
    ACCOUNT_ID: "582662663083"
    REPO_NAME: "apurba-ui"
    AWS_REGION: "us-east-1"
phases: 
  install:
    commands: 
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - echo $COMMIT_HASH
    - apt update -y
    - apt install docker.io -y
    - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
    - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build: 
    commands: 
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build: 
    commands: 
    - docker build -t $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:latest -t $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$COMMIT_HASH .
  post_build: 
    commands: 
    - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:latest
    - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$COMMIT_HASH
    - aws ecs update-service --service "apurba-ui2" --force-new-deployment --cluster "portfolio-cluster" --region "us-east-1"
